function MODEL = build_model(options)
% =========================================================
% 自动创建二级倒立摆 Simulink 模型
% =========================================================

if nargin < 1, options = struct(); end
if ~isfield(options,'show_ui'), options.show_ui = true; end
if ~isfield(options,'show_animation'), options.show_animation = true; end
cacheFolder = fullfile(dp_output_dir(),'cache');
previousConfig = Simulink.fileGenControl('getConfig');
restoreConfig = onCleanup(@() Simulink.fileGenControl('setConfig','config',previousConfig));
Simulink.fileGenControl('set','CacheFolder',cacheFolder, ...
    'CodeGenFolder',fullfile(dp_output_dir(),'codegen'),'createDir',true);
if ~isfield(options,'scenario'), options.scenario = 'swingup'; end
P = dp_scenario_config(options.scenario);

MODEL = 'Double_Pendulum_Project';
if strcmp(options.scenario,'balance'), MODEL = 'Double_Pendulum_Balance'; end

% Reuse the existing project model and rebuild its contents in place.
if bdIsLoaded(MODEL)
    close_system(MODEL,0);
end
sourceModel = fullfile(fileparts(mfilename('fullpath')),'reference',[MODEL '.slx']);
if exist(sourceModel,'file') == 2
    load_system(sourceModel);
    Simulink.BlockDiagram.deleteContents(MODEL);
else
    new_system(MODEL);
end

if options.show_ui, open_system(MODEL); end

rt = sfroot;

%% =========================================================
% Controller
%% =========================================================

controllerPath = [MODEL '/Controller'];

add_block( ...
    'simulink/User-Defined Functions/MATLAB Function', ...
    controllerPath, ...
    'Position',[70 130 300 360]);

% The swing-up controller carries a persistent stage state.  Execute the
% MATLAB Function subsystem at the same discrete rate used by the digital
% controller instead of inheriting the plant's continuous sample time.
set_param(controllerPath,'SystemSampleTime',num2str(P.swingup.numeric_dt));

controllerChart = rt.find( ...
    '-isa','Stateflow.EMChart', ...
    'Path',controllerPath);

controllerChart.Script = sprintf([ ...
'function [u,stage] = fcn(t,x,xdot,theta1,theta1dot,theta2,theta2dot)\n' ...
'[u,stage] = dp_controller(t,x,xdot,theta1,theta1dot,theta2,theta2dot,%d);\n' ...
'end\n'],P.control_mode);

%% Clock

add_block( ...
    'simulink/Sources/Clock', ...
    [MODEL '/Clock'], ...
    'Position',[20 145 45 175]);

%% Saturation

add_block( ...
    'simulink/Discontinuities/Saturation', ...
    [MODEL '/Acceleration_Limit'], ...
    'Position',[350 190 405 230]);

set_param( ...
    [MODEL '/Acceleration_Limit'], ...
    'UpperLimit',num2str(P.u_max), ...
    'LowerLimit',num2str(-P.u_max));

%% =========================================================
% Plant
%% =========================================================

plantPath = [MODEL '/Double_Pendulum_Dynamics'];

add_block( ...
    'simulink/User-Defined Functions/MATLAB Function', ...
    plantPath, ...
    'Position',[480 120 730 360]);

plantChart = rt.find( ...
    '-isa','Stateflow.EMChart', ...
    'Path',plantPath);

plantChart.Script = sprintf([ ...
'function [xddot,theta1ddot,theta2ddot] = fcn(u,theta1,theta1dot,theta2,theta2dot)\n' ...
'[xddot,theta1ddot,theta2ddot] = dp_dynamics(u,theta1,theta1dot,theta2,theta2dot);\n' ...
'end\n']);

%% =========================================================
% Integrators
%% =========================================================

% xdot

add_block( ...
    'simulink/Continuous/Integrator', ...
    [MODEL '/Int_xdot'], ...
    'Position',[800 80 840 110]);

set_param( ...
    [MODEL '/Int_xdot'], ...
    'InitialCondition',num2str(P.xdot0));

% x

add_block( ...
    'simulink/Continuous/Integrator', ...
    [MODEL '/Int_x'], ...
    'Position',[900 80 940 110]);

set_param( ...
    [MODEL '/Int_x'], ...
    'InitialCondition',num2str(P.x0));

%% theta1dot

add_block( ...
    'simulink/Continuous/Integrator', ...
    [MODEL '/Int_theta1dot'], ...
    'Position',[800 190 840 220]);

set_param( ...
    [MODEL '/Int_theta1dot'], ...
    'InitialCondition',num2str(P.theta1dot_0));

%% theta1

add_block( ...
    'simulink/Continuous/Integrator', ...
    [MODEL '/Int_theta1'], ...
    'Position',[900 190 940 220]);

set_param( ...
    [MODEL '/Int_theta1'], ...
    'InitialCondition',num2str(P.theta1_0));

%% theta2dot

add_block( ...
    'simulink/Continuous/Integrator', ...
    [MODEL '/Int_theta2dot'], ...
    'Position',[800 300 840 330]);

set_param( ...
    [MODEL '/Int_theta2dot'], ...
    'InitialCondition',num2str(P.theta2dot_0));

%% theta2

add_block( ...
    'simulink/Continuous/Integrator', ...
    [MODEL '/Int_theta2'], ...
    'Position',[900 300 940 330]);

set_param( ...
    [MODEL '/Int_theta2'], ...
    'InitialCondition',num2str(P.theta2_0));

%% =========================================================
% Scope - x theta1 theta2
%% =========================================================

add_block( ...
    'simulink/Signal Routing/Mux', ...
    [MODEL '/Mux_State'], ...
    'Position',[1030 100 1035 210]);

set_param( ...
    [MODEL '/Mux_State'], ...
    'Inputs','3');

add_block( ...
    'simulink/Sinks/Scope', ...
    [MODEL '/Scope_State'], ...
    'Position',[1110 130 1160 180]);

%% =========================================================
% Scope - velocities
%% =========================================================

add_block( ...
    'simulink/Signal Routing/Mux', ...
    [MODEL '/Mux_Velocity'], ...
    'Position',[1030 270 1035 380]);

set_param( ...
    [MODEL '/Mux_Velocity'], ...
    'Inputs','3');

add_block( ...
    'simulink/Sinks/Scope', ...
    [MODEL '/Scope_Velocity'], ...
    'Position',[1110 300 1160 350]);

add_block('simulink/Sinks/Scope',[MODEL '/Scope_Control'], ...
    'Position',[1110 410 1160 460]);
add_block('simulink/Sinks/Scope',[MODEL '/Scope_Stage'], ...
    'Position',[1110 500 1160 550]);
add_block('simulink/Sinks/To Workspace',[MODEL '/Log_State'], ...
    'VariableName','dp_state_log','SaveFormat','Structure With Time', ...
    'Position',[1200 130 1300 160]);
add_block('simulink/Sinks/To Workspace',[MODEL '/Log_Velocity'], ...
    'VariableName','dp_velocity_log','SaveFormat','Structure With Time', ...
    'Position',[1200 300 1300 330]);
add_block('simulink/Sinks/To Workspace',[MODEL '/Log_Control'], ...
    'VariableName','dp_control_log','SaveFormat','Structure With Time', ...
    'Position',[450 390 550 420]);
add_block('simulink/Sinks/To Workspace',[MODEL '/Log_Stage'], ...
    'VariableName','dp_stage_log','SaveFormat','Structure With Time', ...
    'Position',[450 440 550 470]);

%% =========================================================
% Animation
%% =========================================================

animationPath = [MODEL '/Animation'];

add_block( ...
    'simulink/User-Defined Functions/MATLAB Function', ...
    animationPath, ...
    'Position',[630 470 850 590]);

animationChart = rt.find( ...
    '-isa','Stateflow.EMChart', ...
    'Path',animationPath);

if options.show_animation
    animationChart.Script = sprintf([ ...
    'function y = fcn(t,x,theta1,theta2)\n' ...
    'coder.extrinsic(''dp_animation'');\n' ...
    'dp_animation(t,x,theta1,theta2);\n' ...
    'y = 0;\n' ...
    'end\n']);
else
    animationChart.Script = sprintf([ ...
    'function y = fcn(t,x,theta1,theta2)\n' ...
    'y = 0*t + 0*x + 0*theta1 + 0*theta2;\n' ...
    'end\n']);
end

add_block( ...
    'simulink/Sinks/Terminator', ...
    [MODEL '/Animation_Terminator'], ...
    'Position',[900 515 920 535]);

%% =========================================================
% Update ports
%% =========================================================

set_param(MODEL,'SimulationCommand','update');

%% =========================================================
% Plant connection
%% =========================================================

add_line(MODEL, ...
    'Controller/1', ...
    'Acceleration_Limit/1', ...
    'autorouting','on');

add_line(MODEL, ...
    'Acceleration_Limit/1', ...
    'Double_Pendulum_Dynamics/1', ...
    'autorouting','on');

%% x

add_line(MODEL, ...
    'Double_Pendulum_Dynamics/1', ...
    'Int_xdot/1', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_xdot/1', ...
    'Int_x/1', ...
    'autorouting','on');

%% theta1

add_line(MODEL, ...
    'Double_Pendulum_Dynamics/2', ...
    'Int_theta1dot/1', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta1dot/1', ...
    'Int_theta1/1', ...
    'autorouting','on');

%% theta2

add_line(MODEL, ...
    'Double_Pendulum_Dynamics/3', ...
    'Int_theta2dot/1', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta2dot/1', ...
    'Int_theta2/1', ...
    'autorouting','on');

%% =========================================================
% Plant feedback
%% =========================================================

add_line(MODEL, ...
    'Int_theta1/1', ...
    'Double_Pendulum_Dynamics/2', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta1dot/1', ...
    'Double_Pendulum_Dynamics/3', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta2/1', ...
    'Double_Pendulum_Dynamics/4', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta2dot/1', ...
    'Double_Pendulum_Dynamics/5', ...
    'autorouting','on');

%% =========================================================
% Controller inputs
%% =========================================================

add_line(MODEL, ...
    'Clock/1', ...
    'Controller/1', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_x/1', ...
    'Controller/2', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_xdot/1', ...
    'Controller/3', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta1/1', ...
    'Controller/4', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta1dot/1', ...
    'Controller/5', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta2/1', ...
    'Controller/6', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta2dot/1', ...
    'Controller/7', ...
    'autorouting','on');

%% =========================================================
% State Scope
%% =========================================================

add_line(MODEL, ...
    'Int_x/1', ...
    'Mux_State/1', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta1/1', ...
    'Mux_State/2', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta2/1', ...
    'Mux_State/3', ...
    'autorouting','on');

add_line(MODEL, ...
    'Mux_State/1', ...
    'Scope_State/1', ...
    'autorouting','on');

add_line(MODEL,'Mux_State/1','Log_State/1','autorouting','on');

%% =========================================================
% Velocity Scope
%% =========================================================

add_line(MODEL, ...
    'Int_xdot/1', ...
    'Mux_Velocity/1', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta1dot/1', ...
    'Mux_Velocity/2', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta2dot/1', ...
    'Mux_Velocity/3', ...
    'autorouting','on');

add_line(MODEL, ...
    'Mux_Velocity/1', ...
    'Scope_Velocity/1', ...
    'autorouting','on');

add_line(MODEL,'Mux_Velocity/1','Log_Velocity/1','autorouting','on');
add_line(MODEL,'Acceleration_Limit/1','Scope_Control/1','autorouting','on');
add_line(MODEL,'Acceleration_Limit/1','Log_Control/1','autorouting','on');
add_line(MODEL,'Controller/2','Scope_Stage/1','autorouting','on');
add_line(MODEL,'Controller/2','Log_Stage/1','autorouting','on');

%% =========================================================
% Animation connections
%% =========================================================

add_line(MODEL, ...
    'Clock/1', ...
    'Animation/1', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_x/1', ...
    'Animation/2', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta1/1', ...
    'Animation/3', ...
    'autorouting','on');

add_line(MODEL, ...
    'Int_theta2/1', ...
    'Animation/4', ...
    'autorouting','on');

add_line(MODEL, ...
    'Animation/1', ...
    'Animation_Terminator/1', ...
    'autorouting','on');

%% =========================================================
% Solver
%% =========================================================

if P.control_mode == 4
    set_param(MODEL, ...
        'StopTime',num2str(P.stopTime), ...
        'SolverType','Fixed-step', ...
        'Solver','ode4', ...
        'FixedStep',num2str(P.swingup.numeric_dt));
else
    set_param(MODEL, ...
        'StopTime',num2str(P.stopTime), ...
        'SolverType','Variable-step', ...
        'Solver','ode45', ...
        'MaxStep',num2str(P.maxStep), ...
        'RelTol','1e-7', ...
        'AbsTol','1e-9');
end

%% 自动排版

Simulink.BlockDiagram.arrangeSystem(MODEL);

%% 保存

save_system(MODEL,fullfile(dp_output_dir(),[MODEL '.slx']));

if options.show_ui, open_system(MODEL); end

end
