function MODEL = sp_build_model(scenario,showUI)
%SP_BUILD_MODEL Hardware-free acceleration plant with sampled controller.
if nargin < 1, scenario = 'swingup'; end
if nargin < 2, showUI = true; end
scenario = validatestring(scenario,{'swingup','balance'});
P = sp_config(); balanceOnly = strcmp(scenario,'balance');
if balanceOnly, initial = P.balance_initial; else, initial = P.swing_initial; end
MODEL = ['Single_Pendulum_' scenario];
if bdIsLoaded(MODEL), close_system(MODEL,0); end
new_system(MODEL);
set_param(MODEL,'SolverType','Fixed-step','Solver','ode4', ...
    'FixedStep',num2str(P.dt),'StopTime',num2str(P.stopTime), ...
    'ReturnWorkspaceOutputs','on');
add_block('simulink/Continuous/Integrator',[MODEL '/State'], ...
    'InitialCondition',mat2str(initial,17),'Position',[410 110 450 150]);
add_block('simulink/Discrete/Zero-Order Hold',[MODEL '/Sample_State'], ...
    'SampleTime',num2str(P.dt),'Position',[40 100 75 140]);
add_block('built-in/MATLABFcn', ...
    [MODEL '/Controller'],'Position',[100 100 245 160], ...
    'MATLABFcn',sprintf('sp_control_vector(u,%d)',balanceOnly),'OutputDimensions','2');
add_block('simulink/Signal Routing/Demux',[MODEL '/Command_Stage'], ...
    'Outputs','2','Position',[260 100 265 165]);
add_block('simulink/Signal Routing/Mux',[MODEL '/Plant_Input'], ...
    'Inputs','2','Position',[275 80 280 145]);
add_block('built-in/MATLABFcn',[MODEL '/Nonlinear_Plant'], ...
    'Position',[290 95 375 155],'MATLABFcn','sp_dynamics_vector(u)', ...
    'OutputDimensions','4');
add_block('simulink/Sinks/To Workspace',[MODEL '/State_Log'], ...
    'VariableName','sp_state_log','SaveFormat','Structure With Time', ...
    'Position',[535 105 650 135]);
add_block('simulink/Sinks/To Workspace',[MODEL '/Control_Log'], ...
    'VariableName','sp_control_log','SaveFormat','Structure With Time', ...
    'Position',[290 225 405 255]);
add_block('simulink/Sinks/To Workspace',[MODEL '/Stage_Log'], ...
    'VariableName','sp_stage_log','SaveFormat','Structure With Time', ...
    'Position',[290 285 405 315]);
add_block('simulink/Sinks/Scope',[MODEL '/State_Scope'], ...
    'Position',[545 170 605 210]);
add_line(MODEL,'State/1','Sample_State/1','autorouting','on');
add_line(MODEL,'Sample_State/1','Controller/1','autorouting','on');
add_line(MODEL,'Controller/1','Command_Stage/1','autorouting','on');
add_line(MODEL,'State/1','Plant_Input/1','autorouting','on');
add_line(MODEL,'Command_Stage/1','Plant_Input/2','autorouting','on');
add_line(MODEL,'Plant_Input/1','Nonlinear_Plant/1','autorouting','on');
add_line(MODEL,'Nonlinear_Plant/1','State/1','autorouting','on');
add_line(MODEL,'State/1','State_Log/1','autorouting','on');
add_line(MODEL,'State/1','State_Scope/1','autorouting','on');
add_line(MODEL,'Command_Stage/1','Control_Log/1','autorouting','on');
add_line(MODEL,'Command_Stage/2','Stage_Log/1','autorouting','on');
Simulink.BlockDiagram.arrangeSystem(MODEL);
folder = fullfile(fileparts(fileparts(mfilename('fullpath'))),'output','single_pendulum');
if ~isfolder(folder), mkdir(folder); end
save_system(MODEL,fullfile(folder,[MODEL '.slx']));
if showUI, open_system(MODEL); open_system([MODEL '/State_Scope']); end
end
